"use client";
import React, { useState } from "react";
import { motion } from "framer-motion";
import { Building2, Globe, Phone, Mail, ArrowLeft, MapPin } from "lucide-react";
import Link from "next/link";
export default function OrgRegister() {
  const [formData, setFormData] = useState({ orgname: "", headname: "", category: "", phonenumber: "", email: "", district_id: "", address: "", website: "" });
  const handleChange = (e) => { const { name, value } = e.target; setFormData(prev => ({ ...prev, [name]: value })); };
  return <div className="min-h-screen pt-24 pb-12 bg-slate-50 px-4 text-slate-800"><div className="max-w-4xl mx-auto text-left"><Link href="/signup" className="inline-flex items-center text-indigo-600 mb-6"><ArrowLeft className="w-4 h-4 mr-2" /> Back</Link><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-slate-100"><div className="bg-gradient-to-r from-orange-600 to-red-600 p-8 text-white"><h1 className="text-3xl font-bold mb-2">Organization Registration</h1><p className="text-orange-100 italic font-telugu text-lg">సంస్థ రిజిస్ట్రేషన్ ఫారం</p></div><form className="p-8 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Org Name / సంస్థ పేరు *</label><input required name="orgname" value={formData.orgname} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-orange-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Head Name / ప్రతినిధి పేరు *</label><input required name="headname" value={formData.headname} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-orange-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Phone / ఫోన్ *</label><input required name="phonenumber" value={formData.phonenumber} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-orange-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Category / విభాగం *</label><select required name="category" value={formData.category} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-orange-500 transition-all font-sans"><option value="">Select Category</option><option value="NGO">NGO</option><option value="Trust">Trust</option><option value="Society">Society</option></select></div></div><div className="pt-6"><button type="submit" className="w-full bg-orange-600 text-white font-bold py-4 rounded-2xl shadow-lg hover:bg-orange-700 transition-all text-lg tracking-wider uppercase font-sans">Register Organization</button></div></form></motion.div></div></div>; }
