"use client";
import React, { useState } from "react";
import { motion } from "framer-motion";
import { Church, MapPin, Phone, User, Globe, ArrowLeft } from "lucide-react";
import Link from "next/link";
export default function ChurchRegister() {
  const [formData, setFormData] = useState({ churchname: "", pastorname: "", phonenumber: "", district_id: "", constituency_id: "", mandal_id: "", address: "", denomination: "", founded: "" });
  const handleChange = (e) => { const { name, value } = e.target; setFormData(prev => ({ ...prev, [name]: value })); };
  return <div className="min-h-screen pt-24 pb-12 bg-slate-50 px-4 text-slate-800"><div className="max-w-4xl mx-auto text-left"><Link href="/signup" className="inline-flex items-center text-indigo-600 mb-6"><ArrowLeft className="w-4 h-4 mr-2" /> Back</Link><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-slate-100"><div className="bg-gradient-to-r from-teal-600 to-emerald-600 p-8 text-white"><h1 className="text-3xl font-bold mb-2">Church Registration</h1><p className="text-teal-100 italic font-telugu text-lg">చర్చి రిజిస్ట్రేషన్ ఫారం</p></div><form className="p-8 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Church Name / చర్చి పేరు *</label><input required name="churchname" value={formData.churchname} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-teal-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Pastor Name / పాస్టర్ పేరు *</label><input required name="pastorname" value={formData.pastorname} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-teal-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Contact Number / ఫోన్ *</label><input required name="phonenumber" value={formData.phonenumber} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-teal-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Denomination / శాఖ *</label><input required name="denomination" value={formData.denomination} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-teal-500 transition-all font-sans" /></div></div><div className="pt-6"><button type="submit" className="w-full bg-teal-600 text-white font-bold py-4 rounded-2xl shadow-lg hover:bg-teal-700 transition-all text-lg tracking-wider uppercase font-sans">Register Church</button></div></form></motion.div></div></div>; }
