"use client";
import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Mail, Phone, Lock, MapPin, Globe, Users, Building, ArrowLeft } from "lucide-react";
import Link from "next/link";
export default function MinistryRegister() {
  const [formData, setFormData] = useState({ firstname: "", denomation: "", ministryemail: "", headnmber: "", number_ofchurches: "", number_ofmembers: "", district_id: "", street: "", password: "", retypepassword: "" });
  const handleChange = (e) => { const { name, value } = e.target; setFormData((prev) => ({ ...prev, [name]: value })); };
  return <div className="min-h-screen bg-slate-50 pt-24 pb-12 px-4 shadow-inner text-slate-800"><div className="max-w-4xl mx-auto text-left"><Link href="/signup" className="inline-flex items-center text-indigo-600 mb-6"><ArrowLeft className="w-4 h-4 mr-2" /> Back</Link><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="bg-white rounded-3xl shadow-2xl overflow-hidden shadow-indigo-100/50 border border-slate-100"><div className="bg-gradient-to-r from-indigo-600 to-violet-600 p-8 text-white"><h1 className="text-3xl font-bold mb-2">Ministry Registration</h1><p className="text-indigo-100 italic font-telugu text-lg">మినిస్ట్రీ రిజిస్ట్రేషన్ ఫారం</p></div><form className="p-8 space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Ministry Name / పేరు</label><input required name="firstname" value={formData.firstname} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Contact Number / ఫోన్</label><input required name="headnmber" value={formData.headnmber} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Total Churches / చర్చిలు</label><input required type="number" name="number_ofchurches" value={formData.number_ofchurches} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 transition-all font-sans" /></div><div><label className="block text-sm font-bold text-slate-700 mb-2 font-telugu">Total Members / సభ్యులు</label><input required type="number" name="number_ofmembers" value={formData.number_ofmembers} onChange={handleChange} className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:ring-2 focus:ring-indigo-500 transition-all font-sans" /></div></div><div className="pt-6"><button type="submit" className="w-full bg-indigo-600 text-white font-bold py-4 rounded-2xl shadow-lg hover:bg-indigo-700 transition-all text-lg tracking-wider uppercase font-sans">Register Ministry</button></div></form></motion.div></div></div>; }
